version: '3.7'

services:
  devops_api:
    build:
      context: .
      target: development
    platform: "linux/amd64"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
