apiVersion: v1
kind: Service
metadata:
    name: redis
    labels:
        app: redis
spec:
    ports:
        -   name: redis
            port: 6379
            targetPort: 6379
    type: ClusterIP
    selector:
        app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
spec:
    selector:
        matchLabels:
            app: redis
    replicas: 1
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                -   name: redis
                    image: redis:latest
                    command:
                        - redis-server
                        - "/redis-master/redis.conf"
                    imagePullPolicy: IfNotPresent
                    ports:
                        -   name: redis
                            containerPort: 6379
                    volumeMounts:
                        -   name: data
                            mountPath: /data
                            readOnly: false
                        -   name: config
                            mountPath: /redis-master

            volumes:
                -   name: data
                    persistentVolumeClaim:
                        claimName: redis-data
                -   name: config
                    configMap:
                        name: redis-config
                        items:
                            -   key: redis-config
                                path: redis.conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redis-data
    labels:
        app: redis
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
