apiVersion: v1
kind: Secret
metadata:
    name: nttdata-app-secret
stringData:
    ECR_REGISTRY: {{ env "ECR_REGISTRY" }}
    IMAGE_NAME: {{ env "IMAGE_NAME" }}
    REDIS_HOST: {{ env "REDIS_HOST" }}
    REDIS_PORT: {{ env "REDIS_PORT" }}
    JWT: {{ env "JWT" }}
    API_KEY: {{ env "API_KEY" }}
type: Opaque
