apiVersion: v1
kind: Secret
metadata:
    name: nttdata-app-secret
stringData:
    REDIS_HOST: "redis.redis"
    REDIS_PORT: "6379"
    JWT: "secret"
    API_KEY: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
type: Opaque
