name: AWS CDK Deploy

on:
    push:
        branches:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Prepare
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  cd aws
                  npm ci

            - name: Deploy AWS CDK stack
              run: |
                  cd aws
                  npm run deploy
              env:
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                  AWS_REGION: <AWS region>
