name: CDK Deploy

on:
    push:
        branches:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install AWS CLI and AWS CDK
              uses: aws-actions/setup-aws-cli@v1
              with:
                  aws-region: <AWS region>
                  cdk-version: <CDK version>
            - name: Authenticate with Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              with:
                  registry: <ECR registry>
            - name: Deploy AWS CDK stack
              run: |
                  cd aws
                  npm run deploy
              env:
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                  AWS_REGION: <AWS region>
