name: Build and Push Docker Image

on:
    push:
        branches:
            - '*'

env:
    ECR_REGISTRY: 092746443745.dkr.ecr.sa-east-1.amazonaws.com/cdk-hnb659fds-container-assets-092746443745-sa-east-1
    IMAGE_NAME: nttdata-image
    AWS_REGION: sa-east-1
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              with:
                  registry: ${{ env.ECR_REGISTRY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Build Docker image
              id: build-image
              run: |
                  docker build --target production -t $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA .

            - name: Push Docker image to ECR
              id: push-image
              run: |
                  docker push $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA

            - name: Write image details to file
              run: |
                  echo "::set-output name=image-uri::$ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA"
